### ISSUE TITLE
Simplify function names and make it overridable

### ISSUE THREAD

**Issue by lerenn** [lerenn/asyncapi-codegen#158]
# Current situation

Some function names can be really long because : 
* Using the operation names directly is not recommanded as [we cannot derive the name from sender to receiver and vice/versa](https://www.asyncapi.com/docs/reference/specification/v3.0.0#introduction);
* There can be some ambiguity can appear in some minor cases when mixing messages and channels, so we put the request function as `Request<MsgName>On<ChannelName>ChannelWith<MsgName>On<ChannelName>Channel`.

# Problem

* Really long names. Example: `RequestServiceInfoResponseOnServiceInfoResponseChannelWithServiceInfoRequestOnServiceInfoRequestChannel`
* Not reflecting the operations

# Proposition

## Change function names

* Send: `Send[To (User)/ As (App)]<OperationName>Operation[With<MessageName>]`
* Subscribe: `SubscribeTo<OperationName>Operation[With<MessageName>]`
* Receive: `<OperationName>Operation[With<MessageName>]Received`
* Request:  `RequestTo<OperationName>Operation[With<ReplyMessageName>][With<RequestMessageName>]`
* Reply: `ReplyTo<OperationName>Operation[With<RequestMessageName>][WithReply<MessageName>]`

*Note: `[With<MessageName>]` and others  should be implemented with [issue 140 for multiple messages](https://github.com/lerenn/asyncapi-codegen/issues/140)*

Examples:
* Operation `receiveHello` with side `receive`:
   * Send (*user*): `SendToReceiveHelloOperation`
   * Subscribe (*app*): `SubscribeToReceiveHelloOperation`
   * Receive (*app*): `ReceiveHelloOperationReceived`
   * Request/Reply: N/A
* Operation `sendHello` with side `send`:
   * Send (*app*): `SendAsSendHelloOperation`
   * Subscribe (*user*): `SubscribeToSendHelloOperation`
   * Receive (*user*): `SendHelloOperationReceived`
   * Request/Reply: N/A
 * Operation `pingRequest` with side`receive`:
   * Send (*user*): `SendToPingRequestOperation`
   * Subscribe (*app*): `SubscribeToPingRequestOperation`
   * Receive (*app*): `PingRequestOperationReceived`
   * Request (*user*): `RequestPingRequestOperation`
   * Reply (*app*): `ReplyToPingRequestOperation`
 * Operation `onUserSignedUp` with side `send`:
   * Send (*app*): `SendAsOnUserSignedUpOperation`
   * Subscribe (*user*): `SubscribeToOnUserSignedUpOperation`
   * Receive (*user*): `OnUserSignedUpOperationReceived`
   * Request/Reply: N/A

## Add overwritable function name based on side

Example:

```yaml
operations:
    receiveHello:
       action: receive
       x-go-send-func: SendHello
       x-go-subscribe-func: SubscribeToHello
       x-go-received-func: HelloReceived
```

```yaml
operations:
    pingRequest:
       action: receive
       x-go-send-func: AsyncPing
       x-go-subscribe-func: SubscribeToPing
       x-go-received-func: PingReceived
       x-go-request-func: Ping
       x-go-reply-func: Pong
```

*Note: Could be prefixed with With<Message> if there is multiple messages*
