### ISSUE TITLE
When using message trait, the message generation is broken

### ISSUE THREAD

**Issue by lerenn** [lerenn/asyncapi-codegen#173]
When using a message trait on a message, the struct representing headers is uncorrectly named and the file is not correct as collision occurs as well as non corresponding naming. Example:

```golang
type header struct {
	CorrelationId *string `json:"correlation_id"`
}

// ListResponseMessage is the message expected for 'ListResponseMessage' channel.
type ListResponseMessage struct {
	// Headers will be used to fill the message headers
	Headers Header
```

From

```
components:
  messageTraits:
    withCorrelationID:
      headers:
        type: object
        properties:
          correlationId:
            description: Correlation ID set by client
            type: string
```
