### ISSUE TITLE
Inheritance feature

### ISSUE THREAD

**Issue by codycoach** [lerenn/asyncapi-codegen#192]
Hi,

Since `Asyncapi` claimed that `AsyncAPI is compatible with OpenAPI schemas.`
So it would be great to inherit the schema from `openapi` or an external source file.

For example
```yaml
data:
  type: object
  $ref: './openapi.yml#/components/schemas/hello'
```

see more: https://www.asyncapi.com/docs/tutorials/getting-started/coming-from-openapi
