### ISSUE TITLE
AsyncAPI v3: support `servers` object as a map.

### ISSUE THREAD

**Issue by wizzardich** [lerenn/asyncapi-codegen#209]
## Current Behaviour

Given the following configuration of the `servers` object:

```yaml
servers:
  local:
    host: localhost:9092
    protocol: kafka
    protocolVersion: '3.5'
    description: Local Kafka broker
  test:
    host: test.k8s.cluster.local:9092
    protocol: kafka
    protocolVersion: '3.5'
    description: Test environment K8S Kafka cluster
```

The execution of `asyncapi-codegen` fails while unmarshalling the spec:

```sh
✘ asyncapi-codegen -i api/asyncapi/client/events.yml -o asyncapi.gen.go -g types
Error: json: cannot unmarshal object into Go struct field Specification.servers of type []*asyncapiv3.Server
```

According to the [AsyncAPI v3 specification](https://www.asyncapi.com/docs/reference/specification/v3.0.0#serversObject), the `servers` object is supposed to be a map.

## Expected Behaviour

The objects are unmarshalled correctly according to the AsyncAPI spec.

## Notes
- It seems like the crux of the problem is [here](https://github.com/lerenn/asyncapi-codegen/blob/main/pkg/asyncapi/v3/specification.go#L31).
- The `servers` field names are patterned according to the spec with the `^[A-Za-z0-9_\-]+$` regex, so it probably requires further validation.

PS. Thanks so much for this tool! We actively use `oapi-codegen` in our projects so having a similar toolking for AsyncAPI would be very helpful for us. Kudos!
