### ISSUE TITLE
Generation: add overwriteable type names

### ISSUE THREAD

**Issue by wizzardich** [lerenn/asyncapi-codegen#214]
## Current Behaviour

Given the following spec:

```yaml
components:
  messages:
    EventSuccess:
      payload:
        type: object
        properties:
          event_id:
            type: integer
            description: The id of the event
            x-go-name: EventID 
```

The produced output will have the generated type:

```sh
> asyncapi-codegen -i asyncapi.yml -g types -o gen.gen.go
```

```golang
// EventSuccessMessagePayload is a schema from the AsyncAPI specification required in messages
type EventSuccessMessagePayload struct {
	// Description: The id of the event
	EventId *int64 `json:"event_id"`
}
```

## Desired Behaviour

The `x-go-name` directive is respected, the same way `oapi-codegen` does [here](https://github.com/deepmap/oapi-codegen/blob/a8119c1b09d4415c0a939057adbb229cece2aa77/examples/extensions/xgoname/api.yaml#L4)

```golang
type EventSuccessMessagePayload struct {
	// Description: The id of the event
	EventID *int64 `json:"event_id"`
}
```

## Notes

- Ok, I'm back with more XD
- This is similar to #162. It's handy to be able to overwrite the generated field names, for the consistency of the user's codebase.
