### ISSUE TITLE
Generation: array of object types

### ISSUE THREAD

**Issue by wizzardich** [lerenn/asyncapi-codegen#216]
## Current behaviour

```yaml
components:
  messages:
    EventSuccess:
      payload:
        type: object
        properties:
          event_objects:
            type: array
            items:
              type: object
              properties:
                event_id:
                  type: string
                  description: The identifier of the event
                event_type:
                  type: string
                  description: The type of the event
```

After generation run with `asyncapi-codegen -g types`, I run into the following message:

```golang
// Message 'EventSuccessMessageMessageFromEventSuccessChannel' reference another one at '#/components/messages/EventSuccess'.
// This should be fixed in a future version to allow message override.
// If you encounter this message, feel free to open an issue on this subject
// to let know that you need this functionnality.

// EventSuccessMessagePayload is a schema from the AsyncAPI specification required in messages
type EventSuccessMessagePayload struct {
	EventObjects []ItemSchemaForEventObjectsPropertyFromEventSuccessMessagePayload `json:"event_objects"`
}
```

## Desired behaviour

The object is generated with inlaid types.

## Notes

- It seems like `EventSuccessMessageMessageFromEventSuccessChannel` type name does not correspond to anything

**Comment by lerenn** [comment]
This is clearly a bug, the following part of the spec should be generated and named `ItemSchemaForEventObjectsPropertyFromEventSuccessMessagePayload`:

```
type: object
properties:
  event_id:
    type: string
    description: The identifier of the event
  event_type:
    type: string
    description: The type of the event
```

Probably that the naming should be improved also here.
