### ISSUE TITLE
References and compatibility with OpenApi

### ISSUE THREAD

**Issue by nuttert** [lerenn/asyncapi-codegen#224]
Hey, I use both async(fro streams) and open(for rest) api. And it's quite common case when it's needed to use some structure for requests and streams at the same time:

```
Type:
      payload:
        x-go-type: common.Type
        x-go-type-import: 
          path: /my-module/path
 ```
This approach will work, but it breaks the sense of schemas - I can't use it for other languages and, for instance, front-end developers can't use it.

But official specification provide refs for such cases:
 ```
 Type:
      payload:
          $ref: "../common/schemas/common.yaml#/components/schemas/Type"
  ```
  
And the case not only for open api but also for other schemas for async api e.g. when two services use the same structure.
