### ISSUE TITLE
json struct tags with `omitempty`

### ISSUE THREAD

**Issue by unicod3** [lerenn/asyncapi-codegen#245]
Hello @lerenn , 

Thank you for the initiative and the effort. 

I noticed that when we generate `types`, currently the generator does not append `omitempty` to optional fields. 

It only appends `omitempty` for the validation struct tags and when I try to generate a json all the optional fields are coming as `null`

for example: 
```
components:
  schemas:
    Test:
      type: object
      required:
        - RequiredProp
      properties:
        RequiredProp:
          type: string
        StringProp:
          type: string
          minLength: 2
          maxLength: 5
```
This ends up generating the struct below: 
```
// TestSchema is a schema from the AsyncAPI specification required in messages
type TestSchema struct {
	RequiredProp         string   `json:"RequiredProp" validate:"required"`
	StringProp           *string  `json:"StringProp" validate:"omitempty,min=2,max=5"`
}
```

But I expect it to be: 
```
// TestSchema is a schema from the AsyncAPI specification required in messages
type TestSchema struct {
	RequiredProp         string   `json:"RequiredProp" validate:"required"`
	StringProp           *string  `json:"StringProp, omitempty" validate:"omitempty,min=2,max=5"`
}
```
 is there a way to achive this already? If noo I am happy to try to contribute as well.
