### ISSUE TITLE
Add the ability to ignore format on string properties

### ISSUE THREAD

**Issue by TheSadlig** [lerenn/asyncapi-codegen#255]
Hi!

Since working with time.Time/civil.Date is sometime a bit finicky, especially when unmarshalling JSON/YAML, I would like to propose a new flag `ignore-string-format` that would change the generation to avoid using date/datetime.

Small example:
```
properties:
  DateProp:
    type: string
    format: date
```

Without the flag:
```
type TestSchema struct {
	DateProp     *civil.Date `json:"DateProp"`
}
```

With the flag:
```
type TestSchema struct {
	DateProp     *string `json:"DateProp"`
}
```
