### ISSUE TITLE
how to allow "any" body (map[string]interface{})?

### ISSUE THREAD

**Issue by mkyc** [lerenn/asyncapi-codegen#261]
With OpenAPI when I define component like this: 

```yaml
    Obj1:
      type: object
      description: "Any valid JSON payload to be passed through for processing"
      additionalProperties: true
```
and generate types (using [this generator](https://github.com/oapi-codegen/oapi-codegen)) I will get following type: 

```golang
type Obj1 map[string]interface{}
```

but when I do the same in my AsyncAPI schema I get `Error: json: cannot unmarshal bool into Go struct field Schema.components.schemas.additionalProperties of type asyncapiv3.Schema`

and when I change it to:

```yaml
            additionalProperties:
              type: object
```

I get something like this: 

```golang
type WebhookEventMessagePayload struct {
    Body BodyPropertyFromWebhookEventMessagePayload `json:"body" validate:"required"`
}

type BodyPropertyFromWebhookEventMessagePayload struct {
    AdditionalProperties map[string]AdditionalPropertiesFromBodyPropertyFromWebhookEventMessagePayload `json:"-"`
}

type AdditionalPropertiesFromBodyPropertyFromWebhookEventMessagePayload struct{}
```

and  functions `MarshalJSON` and `UnmarshalJSON` but all that looks super weird. 

AFAICT `AdditionalPropertiesFromBodyPropertyFromWebhookEventMessagePayload` is an empty struct, which means it’s not set up to hold any actual data. 

I'd need to modify generated code in a following way: 

```golang
type AdditionalPropertiesFromBodyPropertyFromWebhookEventMessagePayload struct {
    Raw json.RawMessage `json:"-"`
}
```

or comment half of generated code and place simply something like this: 

```golang
type WebhookEventMessage struct {
    Payload struct {
        Body map[string]interface{} `json:"body" validate:"required"`
    } `json:"payload"`
}
```

So my question is: am I wrong? How should I allow "any" body in message?

**Comment by mkyc** [comment]
Oh, I've found some workaround for this issue. I added `x-go-type` flag like this: 

```yaml
          body:
            type: object
            description: "Any valid JSON payload to be passed through for processing"
            x-go-type: json.RawMessage
```
and also removed `additionalProperties` section. That generates much better code: 

```golang
type WebhookEventMessagePayload struct {
	// Description: Any valid JSON payload to be passed through for processing
	Body json.RawMessage `json:"body" validate:"required"`
}
```

Only leftover is that it still generates following code even if it's no longer used: 

```golang
// BodyPropertyFromWebhookEventMessagePayload is a schema from the AsyncAPI specification required in messages
// Description: Any valid JSON payload to be passed through for processing
type BodyPropertyFromWebhookEventMessagePayload struct{}
```
