### ISSUE TITLE
Invalid generation when using `--force-pointers` with required headers

### ISSUE THREAD

**Issue by TheSadlig** [lerenn/asyncapi-codegen#262]
Hi there,

Where using the flag `--force-pointers` , with headers that are required, the generated code will be invalid.

Example yaml:
```yaml
asyncapi: 2.6.0
info:
  title: Sample App
  version: 1.2.3
components:
  messages:
    Test:
      headers:
        type: object
        required:
          - correlationId
        properties:
          correlationId:
            description: Correlation ID set by user
            type: string
      payload:
        type: string
```

Generates: 
```golang
// brokerMessageToTestMessage
switch {
case k == "correlationId": // Retrieving CorrelationId header
	msg.Headers.CorrelationId = string(v) // <-- v is a pointer here, so it won't work
default:

}
...

// toBrokerMessage
headers["correlationId"] = []byte(msg.Headers.CorrelationId) // <-- msg.Headers.CorrelationId is a pointer here, so it won't work
```

This only happens if the following conditions are present:
- Flag `--force-pointers` is used
- Headers are presents
- Headers are required

I'll see if this can be fixed easily.

Thanks,
TheSadlig
