### ISSUE TITLE
Unable to use $ref pointing to files

### ISSUE THREAD

**Issue by jmottier-niryo** [lerenn/asyncapi-codegen#273]
**Description**
When trying to generate code using AsyncAPI Codegen, I encounter an "invalid reference" error when referencing external yaml files.

**Minimal setup to reproduce**
_asyncapi.yaml_
```yaml
asyncapi: 3.0.0
info:
  title: Minimal AsyncAPI
  version: 1.0.0

components:
  schemas:
    MySchema:
      $ref: "./myschema.yaml"
```

_myschema.yaml_
```yaml
type: object
```

The command run:
```
asyncapi-codegen -i asyncapi.yaml,myschema.yaml -o gen.go
```

**Actual behaviors**
```
Error: error when using AsyncAPI: invalid reference: invalid reference "./myschema.yaml"
```

**Expected behaviors**
The code generation should process the external reference without errors.

**Environment**
OS: Ubuntu 24.04
AsyncAPI Codegen version: any version from latest (v0.45.3) up to v0.39

**Additional Context**
Using an absolute path like $ref: "/myschema.yaml" results in the same error
Placing the file in a subdirectory also produce the same result
