### ISSUE TITLE
Add extension x-omitempty

### ISSUE THREAD

**Issue by vragovR** [lerenn/asyncapi-codegen#275]
## Description

I would like to suggest adding the `x-omitempty` extension to control the inclusion of the `omitempty` tag in JSON tags of generated Go structures.

## Current Behavior

Currently, when generating Go structures from AsyncAPI schemas, all optional fields automatically get the `omitempty` tag in their JSON tags. This means that when these fields are empty or null, they are omitted from the JSON output during marshaling.

## Proposed Solution

The `x-omitempty` extension allows controlling whether the `omitempty` tag is included in the JSON tags of generated Go structures. When set to `false`, the `omitempty` tag won't be added even for optional fields.

For example:

```yaml
schemas:
  User:
    type: object
    properties:
      id:
        type: string
      name:
        type: string
        x-omitempty: false
```

Would generate:

```golang
type User struct {
  Id   *string `json:"id,omitempty"`
  Name *string `json:"name"`
}
```

When marshaling an empty `User` struct to JSON, the `name` field would always be included, even when null: `{"name":null}`.

### Example 1: Disable omitempty

```yaml
properties:
  withoutOmitEmpty:
    type: string
    x-omitempty: false
```

Generated Go code:
```golang
WithoutOmitEmpty *string `json:"withoutOmitEmpty"`
```

### Example 2: Explicitly enable omitempty for required fields

```yaml
required:
  - requiredWithOmitEmpty
properties:
  requiredWithOmitEmpty:
    type: string
    x-omitempty: true
```

Generated Go code:
```golang
RequiredWithOmitEmpty string `json:"requiredWithOmitEmpty,omitempty"`
```

## Reason for Addition

The main reason for adding this extension is to support legacy code. In many existing systems, API consumers expect certain fields to always be present in the JSON output, even when they're null.
